### ISSUE TITLE
envy assumes the package directory is the same as the package name

### ISSUE THREAD

**Issue by amitsaha** [shaunvxc/envy#10]
I could be wrong, but I think `envy` assumes that the package lives in a sub-directory which is of the same name as the package itself (Ref: https://github.com/shaunvxc/envy/blob/c5a08ea6ee4218eb3b66dd97fd1c750faae03dd6/envy/application.py#L99)

It's probably easy to reproduce by having a `setup.py` where the `packages_dir` is set to something else other than `name`.

**Comment by shaunvxc** [comment]
@amitsaha Can you give me more details regarding this? Were you running `envy edit` or `envy sync`?  It would be helpful if you provide some detail of the package structure for which you were having issues, so that I can reproduce!  

Thanks!

**Comment by amitsaha** [comment]
Hi @shaunvxc i was running `envy sync`. I will share an easy reproducer for you in the next days. But for the moment, you _may_ try with a setup.py which has `find_packages()` in it and the package directory is named something other than the package name you use in `setup.py`.

**Comment by shaunvxc** [comment]
@amitsaha can you confirm you were passing `envy sync` the _package_ name and not the _distribution_ name?

`envy` uses the `imp` module to find the location of the package-- so as long as you pass `envy` the **package** name, it should work.

Let me know if otherwise!

**Comment by shaunvxc** [comment]
@amitsaha can you confirm the above please when you have the chance? Would like to close this assuming the above is correct.

Thanks!

**Comment by shaunvxc** [comment]
@amitsaha I'm going to close this.  Re-open please if you are still having issues.
